namespace: sample-goapp

image:
  repository: 192.168.1.36:5000/goapp
  tag: latest
  pullPolicy: IfNotPresent

containerPort: 8080

service:
  name: goapp
  type: NodePort
  port: 8080

env:
  - name: ENV
    value: "staging"

imagePullSecrets:
  - name: image-registry-secret

livenessProbe:
  httpGet:
    path: /
    port: 8080
  initialDelaySeconds: 10
  periodSeconds: 5

readinessProbe:
  httpGet:
    path: /
    port: 8080
  initialDelaySeconds: 5
  periodSeconds: 5

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 256Mi

