namespace: sample-goapp

image:
  repository: 192.168.1.36:5000/goapp
  tag: latest
  pullPolicy: IfNotPresent

containerPort: 8080

service:
  name: goapp
  type: NodePort
  port: 8080

env:
  - name: ENV
    value: "staging"

imagePullSecrets:
  - name: image-registry-secret
