name: Build and Push Go App

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: nexus.local:8083/myrepo/goapp

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Login to Nexus Docker Registry
        run: echo "${{ secrets.NEXUS_PASSWORD }}" | docker login nexus.local:8083 -u ${{ secrets.NEXUS_USERNAME }} --password-stdin

      - name: Build Docker Image
        run: |
          docker build -t $IMAGE_NAME:latest .

      - name: Push Image to Nexus
        run: |
          docker push $IMAGE_NAME:latest

      - name: Trigger Deployment Repo (Optional)
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.PAT_GITHUB }}
          repository: your-org/devops-infra
          event-type: deploy-goapp
          client-payload: '{"image": "nexus.local:8083/myrepo/goapp:latest"}'
