name: Build, Push, and Deploy Go App

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: self-hosted
    env:
      IMAGE_NAME: 192.168.1.36:5000/goapp
      MINIKUBE_HOME: /home/githubrunner/minikube

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Login to Nexus Docker Registry
        run: echo "${{ secrets.NEXUS_PASSWORD }}" | docker login http://192.168.1.36:5000 -u ${{ secrets.NEXUS_USERNAME }} --password-stdin

      - name: Build Docker Image
        run: docker build -t $IMAGE_NAME:latest .

      - name: Push Docker Image to Nexus
        run: docker push $IMAGE_NAME:latest

      - name: Checkout Helm Chart Repo
        uses: actions/checkout@v3
        with:
          repository: your-org/devops-infra
          path: devops-infra
          token: ${{ secrets.PAT_GITHUB }}

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Read pipeline.json
        id: config
        run: |
          echo "CHART=$(jq -r .chart pipeline.json)" >> $GITHUB_ENV
          echo "VALUES_FILE=$(jq -r .valuesFile pipeline.json)" >> $GITHUB_ENV
          echo "RELEASE_NAME=$(jq -r .releaseName pipeline.json)" >> $GITHUB_ENV

      - name: Set up Minikube
        uses: medyagh/setup-minikube@v0.0.13

      - name: Wait for cluster to be ready
        run: kubectl get nodes

      - name: Deploy using Helm
        run: |
          helm upgrade --install $RELEASE_NAME ./devops-infra/helm-charts/$CHART -f $VALUES_FILE

      - name: Print Service URL
        run: minikube service $RELEASE_NAME --url
